from typing import Final

PERIODIC_REPORT_REGISTRY: Final[dict[str, str]] = {
    "증자감자현황": "irdsSttus",
    "배당": "alotMatter",
    "자기주식취득처분": "tesstkAcqsDspsSttus",
    "최대주주현황": "hyslrSttus",
    "최대주주변동": "hyslrChgSttus",
    "소액주주": "mrhlSttus",
    "임원현황": "exctvSttus",
    "직원현황": "empSttus",
    "이사감사개인별보수": "hmvAuditIndvdlBySttus",
    "이사감사전체보수": "hmvAuditAllSttus",
    "개인별보수지급": "indvdlByPay",
    "타법인출자": "otrCprInvstmntSttus",
    "채무증권발행": "detScritsIsuAcmslt",
    "기업어음미상환": "entrprsBilScritsNrdmpBlce",
    "단기사채미상환": "srtpdPsndbtNrdmpBlce",
    "회사채미상환": "cprndNrdmpBlce",
    "신종자본증권미상환": "newCaplScritsNrdmpBlce",
    "조건부자본증권미상환": "cndlCaplScritsNrdmpBlce",
    "회계감사인": "accnutAdtorNmNdAdtOpinion",
    "감사용역체결": "adtServcCnclsSttus",
    "비감사용역계약": "accnutAdtorNonAdtServcCnclsSttus",
    "사외이사변동": "outcmpnyDrctrNdChangeSttus",
    "미등기임원보수": "unrstExctvMendngSttus",
    "이사감사보수승인금액": "drctrAdtAllMendngSttusGmtsckConfmAmount",
    "이사감사보수유형별": "drctrAdtAllMendngSttusMendngPymntamtTyCl",
    "공모자금사용": "pssrpCptalUseDtls",
    "사모자금사용": "prvsrpCptalUseDtls",
    "주식총수현황": "stockTotqySttus",
}

MAJOR_EVENT_REGISTRY: Final[dict[str, str]] = {
    "자산양수도": "astInhtrfEtcPtbkOpt",
    "부도발생": "dfOcr",
    "영업정지": "bsnSp",
    "회생절차": "ctrcvsBgrq",
    "해산사유": "dsRsOcr",
    "유상증자결정": "piicDecsn",
    "무상증자결정": "fricDecsn",
    "유무상증자결정": "pifricDecsn",
    "감자결정": "crDecsn",
    "관리절차개시": "bnkMngtPcbg",
    "소송": "lwstLg",
    "해외상장결정": "ovLstDecsn",
    "해외상장폐지결정": "ovDlstDecsn",
    "해외상장": "ovLst",
    "해외상장폐지": "ovDlst",
    "전환사채발행": "cvbdIsDecsn",
    "신주인수권부사채발행": "bdwtIsDecsn",
    "교환사채발행": "exbdIsDecsn",
    "관리절차중단": "bnkMngtPcsp",
    "상각형조건부자본증권발행": "wdCocobdIsDecsn",
    "자기주식취득결정": "tsstkAqDecsn",
    "자기주식처분결정": "tsstkDpDecsn",
    "자기주식신탁체결": "tsstkAqTrctrCnsDecsn",
    "자기주식신탁해지": "tsstkAqTrctrCcDecsn",
    "영업양수결정": "bsnInhDecsn",
    "영업양도결정": "bsnTrfDecsn",
    "유형자산양수": "tgastInhDecsn",
    "유형자산양도": "tgastTrfDecsn",
    "타법인주식양수": "otcprStkInvscrInhDecsn",
    "타법인주식양도": "otcprStkInvscrTrfDecsn",
    "사채권양수": "stkrtbdInhDecsn",
    "사채권양도": "stkrtbdTrfDecsn",
    "회사합병": "cmpMgDecsn",
    "회사분할": "cmpDvDecsn",
    "회사분할합병": "cmpDvmgDecsn",
    "주식교환이전": "stkExtrDecsn",
}

SECURITIES_REGISTRATION_REGISTRY: Final[dict[str, str]] = {
    "지분증권": "estkRs",
    "채무증권": "bdRs",
    "증권예탁증권": "stkdpRs",
    "합병": "mgRs",
    "주식의포괄적교환이전": "extrRs",
    "분할": "dvRs",
}
